config/routes.rb
Rails.application.routes.draw do

  get 'homes/top'
  #resources :homes
  #root "daily_reports#index"
  root 'homes#top'

  #日報 写真 コメント
  resources :daily_reports do
    resources :report_deliveries
    resources :photos do
      resources :photo_comments
    end    
  end

  #ログイン
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  #管理者
  namespace :admin do
    resources :users
    post 'guest_login', to: 'sessions#guest_login'
  end
  
  # ゲストログイン
  post '/login/guest_login', to: 'sessions#guest_login'
  post '/admin/guest_login', to: 'admin/sessions#guest_login'

  #日報を渡す
  post '/daily_reports/:id/share', to: 'daily_reports#share', as: 'share_daily_report'
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :daily_report

  has_many_attached :images
  has_many :photo_comments, dependent: :destroy

  validates :title,  presence: true, length: { maximum: 30 }
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :login_required

  def index
    @daily_report = DailyReport.find(params[:daily_report_id])
    @photos = Photo.all
  end


  def new
    @daily_report = DailyReport.find(params[:daily_report_id])
    @photo = Photo.new
  end
  

  def create
    @daily_report = DailyReport.find(params[:daily_report_id])
    @photo = @daily_report.photos.build(photo_params)
    if @photo.save
      # redirect_to daily_report_photo_path(@daily_report,@photo)
      redirect_to daily_report_photos_path
    else
      render :new
    end
  end
  

  def show
    @daily_report = DailyReport.find(params[:daily_report_id])
    @photo = Photo.find(params[:id])
    #@photo = @daily_report.photos.find(params[:id])
    @photo_comments = @photo.photo_comments
    @photo_comment = @photo.photo_comments.build
  end

  # def show
  #   @daily_report = DailyReport.find(params[:daily_report_id])
  #   @photo = @daily_report.photos.find(params[:id])
  #   @photo_comments = @photo.photo_comments
  #   @photo_comment = @photo.photo_comments.build
  # end


  def edit
    #@daily_report = DailyReport.find(params[:daily_report_id])
    @photo = Photo.find(params[:id]) 
    @daily_report = @photo.daily_report
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photo_params)
      redirect_to daily_report_photo_path
    end

    #添付画像を個別に削除
    if params[:photo][:image_ids]
      params[:photo][:image_ids].each do |image_id|
        image = @photo.images.find(image_id)
        image.purge
      end
    end
  end

  def destroy
    @photo = Photo.find(params[:id])
    if @photo.destroy
      flash[:notice] = "日報を削除しました"
      redirect_to daily_report_photos_path
    end
  end

  private

  def photo_params
      params.require(:photo).permit(:title, images: [])
  end

  #current_user以外はログイン画面に戻す
  def login_required
    redirect_to new_session_path unless current_user
  end

end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.erb
<%= form_with(model: [@daily_report, @photo]) do |form| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= @photo.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @photo.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
    <div class="field">
      <%= form.label :"タイトル" %>
      <%= form.text_field :title, :placeholder => "例)何々の写真" %>
    </div>
  

    <div class="field">
      <%= form.label :写真を選んでください %>
      <%= form.file_field :images, multiple: true %>
    </div>

    <% if @photo.images.attached? %>
        <p>選択済みの画像（削除する画像にチェックをつけてください）</p>
        <div style="display: flex; flex-wrap: wrap; width: 750px;">
        <% @photo.images.each do |image| %>
        <div style="display: flex; margin:5px 5px 5px 0;">
            <%= form.check_box :image_ids, { multiple: true }, image.id, false %>
            <label for="photo_image_ids_<%= image.id %>" > 
            <%= image_tag image, size: '300x300' %>
            </label>
        </div>
        <% end %>
        </div>
    <% end %>
  
    <div class="actions">
      <%= form.submit"登録する", class: 'btn btn-outline-secondary' %>
      <%= link_to '写真一覧に戻る', daily_report_photos_path,class: 'btn btn-outline-secondary' %>
    </div>
<% end %>

app/views/photos/edit.html.erb
<h1>写真を編集</h1>
<%= render 'form' %>

app/views/photos/index.html.erb
<body>
<p id="notice"><%= notice %></p>
<div class="container py-3">
  <div class="row">
    <div class="col">
        

        <h1>写真一覧</h1>
                <table>
                  <thead>
                    <tr>
                      <th>タイトル</th>
                      <th>枚数</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                  <tbody>
                  <% if @photos %>
                    <% @photos.each do |photo| %>
                      <tr>
                        <td><%= photo.title %></td>
                        <td><%= photo.images.attached? ? 1 : 0 %></td>
                        <td><% photo.images.each do |image| %></td>                
                          <td><a href="<%= url_for(image) %>"></td>
                            <td><%= image_tag image.variant(resize: "5%") %><td>
                          </a> 
                        <td><% end %></td>
                        <td><%= link_to '写真を見る', daily_report_photo_path(@daily_report,photo.id),class: 'btn btn-outline-secondary' %></td>
                        <td><%= link_to '削除', daily_report_photo_path(@daily_report,photo.id) ,method: :delete,data: { confirm: "本当に削除してもいいですか？"},class: "btn btn-outline-danger btn" %></td>
                      </tr>
                    <% end %>
                  <% end %>
                  </tbody>
                </table>
        <br>

        <%= link_to '写真を付け加える', new_daily_report_photo_path,class: 'btn btn-outline-secondary' %>
        <%= link_to '日報に戻る', daily_report_path(@daily_report,@photo),class: 'btn btn-outline-secondary' %>
    </div>
  </div>
</div>

app/views/photos/new.html.erb
<h1>写真</h1>
<%= render 'form' %>

app/views/photos/show.html.erb
<p>
  <h3><strong>タイトル</strong></h3>
  <%= @photo.title %>
</p>

<% if @photo.images.attached? %>
<div style="width: 700px;">
  <p><strong>登録した写真</strong></p>
  <% @photo.images.each do |image| %>
    <a href="<%= url_for(image) %>">
      <%= image_tag image, size: '600x600' %>
    </a> 
  <% end %>
</div>
<%= link_to '写真を編集', edit_daily_report_photo_path(@photo),class: 'btn btn-outline-secondary' %>
<%= link_to '写真一覧に戻る', daily_report_photos_path,class: 'btn btn-outline-secondary' %>
<% end %>






<p>コメント一覧</p>


<h3><id="notice"><%= notice %></h3>
<!-- このcomments_areaというHTMLのidを取得して、そのdivの部分だけを更新する -->
<div id="photo_comments_area">
  <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
  <%= render partial: 'photo_comments/index', locals: { photo_comments: @photo_comments, photo: @photo } %>
</div>

<!-- コメント入力欄をブログの詳細ページに表示するためのrender -->

<%= render partial: 'photo_comments/form', locals: { daily_report: @daily_report, photo_comment: @photo_comment, photo: @photo } %>

<%= link_to '編集', edit_daily_report_photo_path(@photo) %>
<%= link_to '戻る', daily_report_photos_path %>