config/routes.rb
Rails.application.routes.draw do

  get 'homes/top'
  #resources :homes
  #root "daily_reports#index"
  root 'homes#top'

  #日報 写真 コメント
  resources :daily_reports do
    resources :report_deliveries
    resources :photos do
      resources :photo_comments
    end    
  end

  #ログイン
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  #管理者
  namespace :admin do
    resources :users
    post 'guest_login', to: 'sessions#guest_login'
  end
  
  # ゲストログイン
  post '/login/guest_login', to: 'sessions#guest_login'
  post '/admin/guest_login', to: 'admin/sessions#guest_login'

  #日報を渡す
  post '/daily_reports/:id/share', to: 'daily_reports#share', as: 'share_daily_report'
end

app/models/user.rb
class User < ApplicationRecord
    before_destroy :admin_not_delete
    before_update :admin_not_update
    has_many :daily_reports, dependent: :destroy

    #日報閲覧許可
    has_many :report_deliveries
    has_many :delivered_reports, through: :report_deliveries, source: :daily_report
    
    #バリデーション
    validates :name,  presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
    before_validation { email.downcase! }  
    has_secure_password     
    validates :password, length: { minimum: 6 }  

    def guest?
        name == 'Guest User' && email == 'guest@example.com'
    end
    
    def admin_guest?
        guest? && admin
    end

    private

    def admin_not_delete
        throw(:abort) if User.where(admin: true).count == 1 && self.admin == true
    end
    
    def admin_not_update
        throw(:abort) if User.where(admin: true).count == 1 && will_save_change_to_attribute?(:admin, to: false)
    end

    def self.admin_guest
        find_or_create_by!(email: 'admin_guest@example.com') do |user|
          user.password = SecureRandom.urlsafe_base64
          user.name = 'Admin Guest'
          user.admin = true
        end
    end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :admin_user

    def index
        @users = User.all.includes(:daily_reports)
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
          redirect_to user_path(@user.id)
        else
          render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "情報を編集しました！"
            redirect_to daily_reports_path
        else
            render :edit
        end
    end

    def show
        @user = User.find(params[:id])
    end

    # def destroy
    #     @user = User.find(params[:id])
    #     @user.destroy
    #     flash[:notice] = "ユーザーを削除しました"
    #     redirect_to admin_users_path
    # end

    def destroy
        @user = User.find(params[:id])
        if @user.guest? || @user.admin_guest?
          flash[:error] = "ゲストユーザーまたは管理者ゲストは削除できません"
          redirect_to admin_users_path
        else
          @user.destroy
          flash[:success] = "ユーザーを削除しました"
          redirect_to admin_users_path
        end
      end

    private

    def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
    end

    def admin_user
      unless logged_in? && current_user.admin?
          flash[:notice] = "管理者以外はアクセス不可"
          #redirect_to new_session_path
          redirect_to homes_top_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
    
  def new
    # redirect_to user_path(current_user.id) if logged_in? || guest_user
    # @user = User.new
    if logged_in?
      redirect_to user_path(current_user.id)
    else
      @user = User.new
    end
  end

  # def new
  #   redirect_to daily_reports_path if logged_in?
  #   @user = User.new
  # end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    unless @user == current_user || @user == guest_user
      flash[:notice] = "権限がありません"
      redirect_to daily_reports_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "情報を編集しました！"
      redirect_to daily_reports_path
    else
      render :edit
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user || @user == guest_user
      flash[:notice] = "権限がありません"
      redirect_to  daily_reports_path
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def guest_user
    User.find_by(email: 'guest@example.com') || User.new(name: 'Guest', email: 'guest@example.com')
  end
  
  #current_user以外はログイン画面に戻す
  def login_required
    redirect_to homes_top_path unless current_user
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "件のエラー") %> があります。 <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: [:admin, @user], local: true) do |f| %>
  <%= f.label :名前 %>
  <%= f.text_field :name %>

  <%= f.label :メールアドレス %>
  <%= f.email_field :email %>

  <%= f.label :パスワード %>
  <%= f.password_field :password %>

  <%= f.label :確認用パスワード %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :管理者権限 %>
  <%= f.check_box :admin, {checked: @user.admin} %>

  <%= f.submit "登録" %>
<% end %>

app/views/admin/users/edit.html.erb
<h3>管理画面からユーザー編集</h3>
<%= render 'form' %>

app/views/admin/users/index.html.erb
<h1>ユーザー管理画面</h1>
<p><%= notice %></p>
<%= link_to 'ユーザーを登録する',new_admin_user_path, class: 'btn btn-outline-secondary' %>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>ユーザー名</th>
      <th>メールアドレス</th>
      <th>タスク数</th>
      <th>管理権限</th>
      <th>詳細</th>
      <th>編集</th>
      <th>削除</th>
    </tr>
  </thead>
  <% @users.each do |user| %>
    <tbody>
      <tr>
        <th></th>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.daily_reports.count %></td>
        <td><%= user.admin %></td>

        <td><%= link_to '詳細', admin_user_path(user) %></td>
        <td><%= link_to '編集', edit_admin_user_path(user) %></td>
        <td><%= link_to '削除', admin_user_path(user), method: :delete, date: { confirm: '本当に削除してもいいですか？' } , class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/admin/users/new.html.erb
<h3>管理画面からユーザー作成</h3>
<%= render 'form' %>

app/views/admin/users/show.html.erb
<h2><%= @user.name %>さんのタスク一覧</h2>

<table class="table">
  <thead>
    <tr>
      <th></th>
      <th>現場名</th>
      <th>日付</th>
      <th>住所</th>
      <th>作業内容</th>
      <th>使用工具</th>
      <th>作業場所</th>
    </tr>
  </thead>
    <% @user.daily_reports.each do |daily_report| %>
      <tr>
        <th></th>
        <td><%= daily_report.place %></td>
        <td><%= daily_report.date %></td>
        <td><%= daily_report.address %></td>
        <td><%= daily_report.action_content %></td>
        <td><%= daily_report.tool %></td>
        <td>
          <% daily_report.labels.each do |label| %>
            <%= label.name %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
<%= link_to '戻る', admin_users_path %>