config/routes.rb
Rails.application.routes.draw do

  get 'homes/top'
  #resources :homes
  #root "daily_reports#index"
  root 'homes#top'

  #日報 写真 コメント
  resources :daily_reports do
    resources :report_deliveries
    resources :photos do
      resources :photo_comments
    end    
  end

  #ログイン
  resources :sessions, only: [:new, :create, :destroy]
  resources :users

  #管理者
  namespace :admin do
    resources :users
    post 'guest_login', to: 'sessions#guest_login'
  end
  
  # ゲストログイン
  post '/login/guest_login', to: 'sessions#guest_login'
  post '/admin/guest_login', to: 'admin/sessions#guest_login'

  #日報を渡す
  post '/daily_reports/:id/share', to: 'daily_reports#share', as: 'share_daily_report'
end

app/models/photo_comment.rb
class PhotoComment < ApplicationRecord
  belongs_to :photo

  validates :comment,  presence: true, length: { maximum: 500 }
end

app/controllers/photo_comments_controller.rb
class PhotoCommentsController < ApplicationController
  before_action :login_required
  # コメントを保存、投稿するためのアクションです。
  def create
    @daily_report = DailyReport.find(params[:daily_report_id])
    # Photoをパラメータの値から探し出し,Photoに紐づくphoto_commentsとしてbuildします。
    @photo = Photo.find(params[:photo_id])
    @photo_comment = @photo.photo_comments.build(photo_comment_params)
    # クライアント要求に応じてフォーマットを変更
    respond_to do |format|
      if @photo_comment.save
        format.js { render :index }
        #format.html { redirect_to blog_path(@photo) }
      else
        #format.js { render :index }
        #flash[:notice] = 'コメント欄が空白です↓'
        format.html { redirect_to daily_report_photo_path(@daily_report, @photo), notice: 'コメント欄が空白です' }
        flash[:notice]
      end
    end
  end

  def show
    @photo = Photo.find(params[:id])
    @photo_comment = @photo.photo_comments.build
    @photo_comments = @photo.photo_comments
  end

  def edit
    @daily_report = DailyReport.find(params[:daily_report_id])
    @photo = Photo.find(params[:photo_id])
    @photo_comment = @photo.photo_comments.find(params[:id])
    respond_to do |format|
      flash.now[:notice] = 'コメントの編集中'
      format.js { render :edit }
    end
  end

  def update
    @photo = Photo.find(params[:photo_id])
    @photo_comment = @photo.photo_comments.find(params[:id])
      respond_to do |format|
        if @photo_comment.update(photo_comment_params)
          flash.now[:notice] = 'コメントが編集されました'
          format.js { render :index }
        else
          flash.now[:notice] = 'コメントの編集に失敗しました'
          format.js { render :edit }
        end
      end
  end

  def destroy
    @photo_comment = PhotoComment.find(params[:id])
    @photo_comment.destroy
    respond_to do |format|
      flash.now[:notice] = 'コメントが削除されました'
      format.js { render :index }
    end
  end

  private
  # ストロングパラメーター
  def photo_comment_params
    params.require(:photo_comment).permit(:comment)
  end
  # def set_blog
  #   @photo = Photo.find(params[:photo_id])
  # end

  #current_user以外はログイン画面に戻す
  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/helpers/photo_comments_helper.rb
module PhotoCommentsHelper
end

app/views/photo_comments/_edit.html.erb
<%= form_with(model: [@daily_report, @photo, @photo_comment], local: false) do |form| %>
    <% if photo_comment.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(photo_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
        <ul>
        <% photo_comment.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= form.text_area :comment, id: "photo_comment_comment_#{photo.id}" %>
      <%= form.label :comment %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
<% end %>

app/views/photo_comments/_form.html.erb
<!-- この記述がphotoのshow画面に表示されるコメント入力欄になります -->

<%= form_with(model: [@daily_report, @photo, @photo_comment],local: false) do |form| %>
  <% if photo_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo_comment.errors.count, "error") %> prohibited this comment from being saved:</h2>
      <ul>
      <% photo_comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="field">
    <%= form.label :コメント %>
    <%= form.text_area :comment, :placeholder => "例)どういう写真でここが何々になってます" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photo_comments/_index.html.erb
<ul>
  <% photo_comments.each do |photo_comment| %>
    <% if photo_comment.id.present? %>
      <li>
        <div class="comment-content" id ="this_photo_comment_<%= photo_comment.id %>"></div>
        <p><%= photo_comment.comment %></p>
        <p><%= link_to "コメント編集", edit_daily_report_photo_photo_comment_path(photo.daily_report_id ,photo, photo_comment), remote: true %></p>
        <p><%= link_to "コメント削除", daily_report_photo_photo_comment_path(photo.daily_report_id, photo_comment.photo_id, photo_comment.id), method: :delete, remote: true,
                                        data: { confirm: "本当に削除しますか?"} %></p>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/photo_comments/edit.js.erb
$("#this_photo_comment_<%= @photo_comment.id %>").replaceWith("<%= j render 'photo_comments/edit', photo: @photo, photo_comment: @photo_comment %>");
$("#notice").html("<%= j flash[:notice] %>");

app/views/photo_comments/index.js.erb
$("#photo_comments_area").html("<%= j(render 'photo_comments/index', {daily_report: @photo_comment.photo.daily_report, photo_comments: @photo_comment.photo.photo_comments, photo: @photo_comment.photo }) %>");
$("textarea").val('');
$("#notice").html("<%= j flash[:notice] %>");

app/views/photo_comments/show.html.erb
<h1>PhotoComments#show</h1>
<p>Find me in app/views/photo_comments/show.html.erb</p>